### ISSUE TITLE
jshint 실행시 에러 발생

### ISSUE THREAD

**Issue by devsejong** [changhwa/daily-commit#14]
app.coffee
-  ⚠  line 70  Line exceeds maximum allowed length                  Length is 152, max is 120
-  ✖  line 72  Function arrows (-> and =>) must be spaced properly

index.coffee
- ✖  line 26  Function arrows (-> and =>) must be spaced properly
- ✖ 1 error

위와 같이 두 파일에 대해서 에러가 발생하는 중

**Comment by changhwa** [comment]
감사합니다. 오늘 저녁 반영 예정입니다.
